// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_
#define FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace Schema {

struct Person;
struct PersonBuilder;

struct Group;
struct GroupBuilder;

struct Client;
struct ClientBuilder;

enum Type : uint8_t {
  Type_NONE = 0,
  Type_Person = 1,
  Type_Group = 2,
  Type_MIN = Type_NONE,
  Type_MAX = Type_Group
};

inline const Type (&EnumValuesType())[3] {
  static const Type values[] = {
    Type_NONE,
    Type_Person,
    Type_Group
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[4] = {
    "NONE",
    "Person",
    "Group",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_NONE, Type_Group)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

template<typename T> struct TypeTraits {
  static const Type enum_value = Type_NONE;
};

template<> struct TypeTraits<Schema::Person> {
  static const Type enum_value = Type_Person;
};

template<> struct TypeTraits<Schema::Group> {
  static const Type enum_value = Type_Group;
};

bool VerifyType(::flatbuffers::Verifier &verifier, const void *obj, Type type);
bool VerifyTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Person FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PersonBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_AGE = 6,
    VT_WEIGHT = 8,
    VT_GENDER = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint16_t age() const {
    return GetField<uint16_t>(VT_AGE, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 0.0f);
  }
  const ::flatbuffers::String *gender() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GENDER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint16_t>(verifier, VT_AGE, 2) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           VerifyOffset(verifier, VT_GENDER) &&
           verifier.VerifyString(gender()) &&
           verifier.EndTable();
  }
};

struct PersonBuilder {
  typedef Person Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Person::VT_NAME, name);
  }
  void add_age(uint16_t age) {
    fbb_.AddElement<uint16_t>(Person::VT_AGE, age, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(Person::VT_WEIGHT, weight, 0.0f);
  }
  void add_gender(::flatbuffers::Offset<::flatbuffers::String> gender) {
    fbb_.AddOffset(Person::VT_GENDER, gender);
  }
  explicit PersonBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Person> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Person>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Person> CreatePerson(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint16_t age = 0,
    float weight = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> gender = 0) {
  PersonBuilder builder_(_fbb);
  builder_.add_gender(gender);
  builder_.add_weight(weight);
  builder_.add_name(name);
  builder_.add_age(age);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Person> CreatePersonDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint16_t age = 0,
    float weight = 0.0f,
    const char *gender = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto gender__ = gender ? _fbb.CreateString(gender) : 0;
  return Schema::CreatePerson(
      _fbb,
      name__,
      age,
      weight,
      gender__);
}

struct Group FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_AGE = 6,
    VT_WEIGHT = 8,
    VT_LIST = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  float age() const {
    return GetField<float>(VT_AGE, 0.0f);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *list() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_LIST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_AGE, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           VerifyOffset(verifier, VT_LIST) &&
           verifier.VerifyVector(list()) &&
           verifier.VerifyVectorOfStrings(list()) &&
           verifier.EndTable();
  }
};

struct GroupBuilder {
  typedef Group Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Group::VT_NAME, name);
  }
  void add_age(float age) {
    fbb_.AddElement<float>(Group::VT_AGE, age, 0.0f);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(Group::VT_WEIGHT, weight, 0.0f);
  }
  void add_list(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> list) {
    fbb_.AddOffset(Group::VT_LIST, list);
  }
  explicit GroupBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Group> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Group>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Group> CreateGroup(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float age = 0.0f,
    float weight = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> list = 0) {
  GroupBuilder builder_(_fbb);
  builder_.add_list(list);
  builder_.add_weight(weight);
  builder_.add_age(age);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Group> CreateGroupDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float age = 0.0f,
    float weight = 0.0f,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *list = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto list__ = list ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*list) : 0;
  return Schema::CreateGroup(
      _fbb,
      name__,
      age,
      weight,
      list__);
}

struct Client FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_CLIENT_DATA_TYPE = 6,
    VT_CLIENT_DATA = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  Schema::Type client_data_type() const {
    return static_cast<Schema::Type>(GetField<uint8_t>(VT_CLIENT_DATA_TYPE, 0));
  }
  const void *client_data() const {
    return GetPointer<const void *>(VT_CLIENT_DATA);
  }
  template<typename T> const T *client_data_as() const;
  const Schema::Person *client_data_as_Person() const {
    return client_data_type() == Schema::Type_Person ? static_cast<const Schema::Person *>(client_data()) : nullptr;
  }
  const Schema::Group *client_data_as_Group() const {
    return client_data_type() == Schema::Type_Group ? static_cast<const Schema::Group *>(client_data()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_CLIENT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_CLIENT_DATA) &&
           VerifyType(verifier, client_data(), client_data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Schema::Person *Client::client_data_as<Schema::Person>() const {
  return client_data_as_Person();
}

template<> inline const Schema::Group *Client::client_data_as<Schema::Group>() const {
  return client_data_as_Group();
}

struct ClientBuilder {
  typedef Client Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Client::VT_NAME, name);
  }
  void add_client_data_type(Schema::Type client_data_type) {
    fbb_.AddElement<uint8_t>(Client::VT_CLIENT_DATA_TYPE, static_cast<uint8_t>(client_data_type), 0);
  }
  void add_client_data(::flatbuffers::Offset<void> client_data) {
    fbb_.AddOffset(Client::VT_CLIENT_DATA, client_data);
  }
  explicit ClientBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Client> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Client>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Client> CreateClient(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    Schema::Type client_data_type = Schema::Type_NONE,
    ::flatbuffers::Offset<void> client_data = 0) {
  ClientBuilder builder_(_fbb);
  builder_.add_client_data(client_data);
  builder_.add_name(name);
  builder_.add_client_data_type(client_data_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Client> CreateClientDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Schema::Type client_data_type = Schema::Type_NONE,
    ::flatbuffers::Offset<void> client_data = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Schema::CreateClient(
      _fbb,
      name__,
      client_data_type,
      client_data);
}

inline bool VerifyType(::flatbuffers::Verifier &verifier, const void *obj, Type type) {
  switch (type) {
    case Type_NONE: {
      return true;
    }
    case Type_Person: {
      auto ptr = reinterpret_cast<const Schema::Person *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Type_Group: {
      auto ptr = reinterpret_cast<const Schema::Group *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyType(
        verifier,  values->Get(i), types->GetEnum<Type>(i))) {
      return false;
    }
  }
  return true;
}

inline const Schema::Client *GetClient(const void *buf) {
  return ::flatbuffers::GetRoot<Schema::Client>(buf);
}

inline const Schema::Client *GetSizePrefixedClient(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Schema::Client>(buf);
}

inline bool VerifyClientBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Schema::Client>(nullptr);
}

inline bool VerifySizePrefixedClientBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Schema::Client>(nullptr);
}

inline void FinishClientBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Schema::Client> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedClientBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Schema::Client> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Schema

#endif  // FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_
